/*
 *
 * AssignmentContainer constants
 *
 */

export const GET_PORTFOLIO_ASSIGNMENT_CLASSES =
  'app/AssignmentContainer/GET_PORTFOLIO_ASSIGNMENT_CLASSES';
export const SET_PORTFOLIO_ASSIGNMENT_CLASSES =
  'app/AssignmentContainer/SET_PORTFOLIO_ASSIGNMENT_CLASSES';
export const GET_PORTFOLIO_ASSIGNMENT_CLASSES_ASS_LIST =
  'app/AssignmentContainer/GET_PORTFOLIO_ASSIGNMENT_CLASSES_ASS_LIST';
export const SET_PORTFOLIO_ASSIGNMENT_CLASSES_ASS_LIST =
  'app/AssignmentContainer/SET_PORTFOLIO_ASSIGNMENT_CLASSES_ASS_LIST';
export const GET_PORTFOLIO_ASSIGNMENT_CLASSES_ASS_LIST_TEMP =
  'app/AssignmentContainer/GET_PORTFOLIO_ASSIGNMENT_CLASSES_ASS_LIST_TEMP';
