export const SKILL_ASSESTMENT_QUESTION_1 = '1';
export const SKILL_ASSESTMENT_QUESTION_2 = '2';
export const SKILL_ASSESTMENT_COMMENT_ROWS = 8;
export const SKILL_ASSESTMENT_COMMENT_COLS = 50;
export const SKILL_ASSESTMENT_INDEX0 = '0';
export const SKILL_ASSESTMENT_INDEX1 = '1';
export const SKILL_ASSESTMENT_PROGRAM_SCORE = 'score';
export const SKILL_ASSESTMENT_PROGRAM_COMMENT = 'comment';
