/*
 *
 * StudentWorkProgramsContainer constants
 *
 */

export const GET_IREAD_STUDENT_WORK_DATA = 'app/GET_IREAD_STUDENT_WORK_DATA';
export const GET_IREAD_STUDENT_WORK_DATA_SUCCESS = 'app/GET_IREAD_STUDENT_WORK_DATA_SUCCESS';
export const GET_IREAD_STUDENT_WORK_DATA_FAILURE = 'app/GET_IREAD_STUDENT_WORK_DATA_FAILURE';
export const POST_IREAD_STUDENT_WORK_DATA = 'app/POST_IREAD_STUDENT_WORK_DATA';
export const SAVE_IREAD_STUDENT_WORK_DATA_REQUEST_SUCCESS =
  'app/SAVE_IREAD_STUDENT_WORK_DATA_REQUEST_SUCCESS';
export const SAVE_IREAD_STUDENT_WORK_DATA_REQUEST_FAILURE =
  'app/SAVE_IREAD_STUDENT_WORK_DATA_REQUEST_FAILURE';
export const DELETE_IREAD_STUDENT_WORK = 'app/DELETE_IREAD_STUDENT_WORK';
export const DELETE_IREAD_STUDENT_WORK_SUCCESS = 'app/DELETE_IREAD_STUDENT_WORK_SUCCESS';
export const DELETE_IREAD_STUDENT_WORK_FAILURE = 'app/DELETE_IREAD_STUDENT_WORK_FAILURE';
export const SHOW_DELETE_MODAL = 'app/SHOW_DELETE_MODAL';
