/*
 *
 * SearchModalContainer constants
 *
 */

export const RESET_SEARCH_META_DATA_REQUEST =
  'app/SearchModalContainer/RESET_SEARCH_META_DATA_REQUEST';
export const RESET_SEARCH_RESULTS_REQUEST = 'app/SearchModalContainer/RESET_SEARCH_RESULTS_REQUEST';
export const RESET_FOR_SEARCH_BY_CHANGE_REQUEST =
  'app/SearchModalContainer/RESET_FOR_SEARCH_BY_CHANGE_REQUEST';
export const DEFAULT_ACTION = 'app/SearchModalContainer/DEFAULT_ACTION';
export const GET_SEARCH_META_DATA_REQUEST = 'app/SearchModalContainer/GET_SEARCH_META_DATA_REQUEST';
export const GET_SEARCH_META_DATA_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_SEARCH_META_DATA_REQUEST_SUCCESS';

export const GET_APPS_FOR_SEARCH_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_APPS_FOR_SEARCH_REQUEST_SUCCESS';
export const GET_CLASSES_FOR_SEARCH_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_CLASSES_FOR_SEARCH_REQUEST_SUCCESS';
export const GET_GRADES_FOR_SEARCH_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_GRADES_FOR_SEARCH_REQUEST_SUCCESS';
export const GET_SCHOOLS_FOR_SEARCH_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_SCHOOLS_FOR_SEARCH_REQUEST_SUCCESS';
export const GET_TEACHERS_FOR_SEARCH_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_TEACHERS_FOR_SEARCH_REQUEST_SUCCESS';

export const GET_SEARCH_META_DATA_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_SEARCH_META_DATA_REQUEST_FAILURE';

export const GET_APPS_FOR_SEARCH_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_APPS_FOR_SEARCH_REQUEST_FAILURE';
export const GET_CLASSES_FOR_SEARCH_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_CLASSES_FOR_SEARCH_REQUEST_FAILURE';
export const GET_GRADES_FOR_SEARCH_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_GRADES_FOR_SEARCH_REQUEST_FAILURE';
export const GET_SCHOOLS_FOR_SEARCH_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_SCHOOLS_FOR_SEARCH_REQUEST_FAILURE';
export const GET_TEACHERS_FOR_SEARCH_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_TEACHERS_FOR_SEARCH_REQUEST_FAILURE';

export const GET_SEARCH_RESULTS_REQUEST = 'app/SearchModalContainer/GET_SEARCH_RESULTS_REQUEST';
export const GET_SEARCH_RESULTS_REQUEST_FAILURE =
  'app/SearchModalContainer/GET_SEARCH_RESULTS_REQUEST_FAILURE';
export const GET_SEARCH_RESULTS_REQUEST_SUCCESS =
  'app/SearchModalContainer/GET_SEARCH_RESULTS_REQUEST_SUCCESS';

export const SEARCH_TEACHER = 'teacher';
export const SEARCH_STUDENT = 'student';
export const UNINITIALIZED_ITEM_COUNT = -1;
