const fm = {
  fm_grading_tools_main: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_05: {
    district: {
      dateRanges: ['StartOfOperation', 'Last3Months', 'CurrSchoolYear', 'Custom'],
      option_name: 'Grouping',
      option_labels: ['Grade', 'School'],
      option_values: ['grade', 'school'],
      option_default: 'grade',
      option_property: 'group_by',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&group_by=$GROUP_BY$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&operation=$OPERATION$&sortOrder=$SORT_ORDER$',
    },
    school: {
      dateRanges: ['StartOfOperation', 'Last3Months', 'CurrSchoolYear', 'Custom'],
      option_name: 'Grouping',
      option_labels: ['Grade', 'Teacher'],
      option_values: ['grade', 'teacher'],
      option_default: 'grade',
      option_property: 'group_by',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&group_by=$GROUP_BY$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&operation=$OPERATION$&sortOrder=$SORT_ORDER$',
    },
    grade: {
      dateRanges: ['StartOfOperation', 'Last3Months', 'CurrSchoolYear', 'Custom'],
      option_name: 'Grouping',
      option_labels: ['Class'],
      option_values: ['class'],
      option_default: 'class',
      option_property: 'group_by',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&group_by=$GROUP_BY$&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&operation=$OPERATION$&sortOrder=$SORT_ORDER$',
    },
  },
  fm_06: {
    district: {
      dateRanges: ['CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    school: {
      dateRanges: ['CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    grade: {
      dateRanges: ['CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: ['CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_13: {
    district: {
      dateRanges: ['CurrSchoolYear', 'CurrGradingPeriod', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    school: {
      dateRanges: ['CurrSchoolYear', 'CurrGradingPeriod', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  fm_settings_main: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/fasttmath/FMProdCtrls?sid=$SESSION_ID$&command=getSettings&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&output_format=raw',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_settings_advanced: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/fasttmath/FMProdCtrls?sid=$SESSION_ID$&command=getSettings&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&output_format=raw',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_02: {
    grade: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  fm_07: {
    grade: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['All Operations', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['all', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'all',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  worksheets_generate: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/fasttmath/FMReportPDF?sid=$SESSION_ID$&report_type_id=fm_10&cohort_type=teacher',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_worksheets_generate: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/fasttmath/FMReportAccess?sid=$SESSION_ID$&command=get_report_pdf&report_type_id=fm_10&cohort_type=student&cohort_id=$STUDENT_ID$&date_range=StartOfOperation&current=$CURRENT$&addition=$ADDITION$&subtraction=$SUBTRACTION$&multiplication=$MULTIPLICATION$&division=$DIVISION$&problem_type=$PROBLEM_TYPE$&orientation=$ORIENTATION$&remainder=$REMAINDER$&answer_key=$ANSWER_KEY$&output_format=raw',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_01: {
    teacher: {
      dateRanges: ['StartOfOperation', 'LastWeek', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['StartOfOperation', 'LastWeek', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['StartOfOperation', 'LastWeek', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: ['StartOfOperation', 'LastWeek', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_03: {
    teacher: {
      dateRanges: ['StartOfOperation', 'Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['StartOfOperation', 'Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['StartOfOperation', 'Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: ['StartOfOperation', 'Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: 'Operation',
      option_labels: ['Current', 'Addition', 'Subtraction', 'Multiplication', 'Division'],
      option_values: ['current', 'addition', 'subtraction', 'multiplication', 'division'],
      option_default: 'current',
      option_property: 'operation',
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&operation=$OPERATION$&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  fm_04: {
    teacher: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: ['Last30Days', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  fm_08: {
    teacher: {
      dateRanges: ['CurrSchoolYear'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['CurrSchoolYear'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['CurrSchoolYear'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  fm_09: {
    teacher: {
      dateRanges: ['CurrSchoolYear'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
};
export default fm;
