const ra = {
  ra_settings_main: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_grading_tools_main: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_01: {
    district: {
      dateRanges: ['CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    school: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_02: {
    district: {
      dateRanges: ['CurrSchoolYear', 'ThisWeek', 'LastWeek', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    school: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_03: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_05: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_06: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_07: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_09: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_10: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_11: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_13: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_15: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_17: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_19: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement0=$CHOICE_CLUSTER$&sortByElement0=$SORT_BY_0$&sortOrder0=$SORT_ORDER_0$&sortOnElement1=$SORT_ON_1$&sortByElement1=$SORT_BY_1$&clusterName=$CLUSTER_NAME$&sortOrder1=$SORT_ORDER_1$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement0=$CHOICE_CLUSTER$&sortByElement0=$SORT_BY_0$&sortOrder0=$SORT_ORDER_0$&sortOnElement1=$SORT_ON_1$&sortByElement1=$SORT_BY_1$&clusterName=$CLUSTER_NAME$&sortOrder1=$SORT_ORDER_1$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement0=$CHOICE_CLUSTER$&sortByElement0=$SORT_BY_0$&sortOrder0=$SORT_ORDER_0$&sortOnElement1=$SORT_ON_1$&sortByElement1=$SORT_BY_1$&clusterName=$CLUSTER_NAME$&sortOrder1=$SORT_ORDER_1$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement0=$CHOICE_CLUSTER$&sortByElement0=$SORT_BY_0$&sortOrder0=$SORT_ORDER_0$&sortOnElement1=$SORT_ON_1$&sortByElement1=$SORT_BY_1$&clusterName=$CLUSTER_NAME$&sortOrder1=$SORT_ORDER_1$',
      pdf_o_qs: null,
    },
  },
  ra_20: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_23eng: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_23sp: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_24eng: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_24sp: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_25: {
    grade: {
      dateRanges: ['Today'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: ['Today'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: ['Today'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: ['Today'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: ['Today'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  ra_30: {
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_26: {
    teacher: {
      dateRanges: [
        'Last15Days',
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  ra_28: {
    teacher: {
      dateRanges: [
        'Last15Days',
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
};
export default ra;
