const xt = {
  xt_settings_main: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_settings_2ptscoring: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/xSkills/XTProductCtrls?sid=$SESSION_ID$&command=get_xskills_settings&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_settings_4ptscoring: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/xSkills/XTProductCtrls?sid=$SESSION_ID$&command=get_xskills_settings&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_settings_6ptscoring: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/xSkills/XTProductCtrls?sid=$SESSION_ID$&command=get_xskills_settings&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_grading_tools_main: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url: null,
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_01: {
    district: {
      dateRanges: ['Last15Days', 'ThisWeek', 'LastWeek', 'CurrSchoolYear', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&testId=$TEST_ID$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    school: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&testId=$TEST_ID$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    grade: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&testId=$TEST_ID$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&testId=$TEST_ID$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&testId=$TEST_ID$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&testId=$TEST_ID$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  xt_02: {
    district: {
      dateRanges: ['CurrSchoolYear', 'ThisWeek', 'LastWeek', 'Custom'],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    school: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    grade: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&school_id=$SCHOOL_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  xt_settings_enrollment: {
    '': {
      dateRanges: [],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        'slms/SlmsDistrict?sid=$SESSION_ID$&command=get_enrollment&district_id=$DISTRICT_ID$&paginate=true&cur_pg=$CURRENT_PAGE$&ipp=500',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_03: {
    grade: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$&courseLevel=$COURSE_LEVEL$',
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$&courseLevel=$COURSE_LEVEL$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$&courseLevel=$COURSE_LEVEL$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$&courseLevel=$COURSE_LEVEL$',
      pdf_o_qs: null,
    },
  },
  xt_06: {
    grade: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    teacher: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
  },
  xt_04: {
    teacher: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'Last15Days',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'CurrSchoolYear',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
  xt_05: {
    teacher: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    class: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    group: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs: null,
      pdf_o_qs: null,
    },
    student: {
      dateRanges: [
        'CurrSchoolYear',
        'CurrGradingPeriod',
        'GradingPeriod1',
        'GradingPeriod2',
        'GradingPeriod3',
        'GradingPeriod4',
        'GradingPeriod5',
        'GradingPeriod6',
        'ThisWeek',
        'LastWeek',
        'Today',
        'Custom',
      ],
      option_name: null,
      option_labels: null,
      option_values: null,
      option_default: null,
      option_property: null,
      connect_url:
        '/slms/SlmsReport?sid=$SESSION_ID$&command=generate_report&report_type_id=$REPORT_TYPE_ID$&user_id=$USER_ID$&cohort_type=$FAMILY$&cohort_id=$COHORT_ID$&date_range=$DATE_RANGE$&attribute_filters=$ATTRIBUTE_FILTERS$&group_filters=$GROUP_FILTERS$&grade_filters=$GRADE_FILTERS$&app_filters=$APP_FILTERS$&item_type=student&school_id=$SCHOOL_ID$',
      pdf_qs:
        '?sortOnElement=$SORT_ON$&sortByElement=$SORT_BY$&courseLevel=$COURSE_LEVEL$&sortOrder=$SORT_ORDER$',
      pdf_o_qs: null,
    },
  },
};
export default xt;
