/*
 *
 * ModalController constants
 *
 */

export const SHOW_MODAL = 'app/ModalController/SHOW_MODAL';
export const HIDE_MODAL = 'app/ModalController/HIDE_MODAL';

// Please keep constants in Alphabetical order
export const ABOUT_LINK_MODAL = 'ABOUT_LINK_MODAL';
export const ACCOUNT_DELETE_MODAL = 'ACCOUNT_DELETE_MODAL';
export const ACTIVATE_QUIZ_MODAL = 'ACTIVATE_QUIZ_MODAL';
export const ADD_A_GROUP = 'ADD_A_GROUP';
export const ADD_DEMOGRAPHIC_MODAL = 'ADD_DEMOGRAPHIC_MODAL';

export const CANCEL_CREDENTIALS_MODAL = 'CANCEL_CREDENTIALS_MODAL';
export const CLASS_FORM_MODAL = 'CLASS_FORM_MODAL';
export const CLEAR_ROSTER_MODAL = 'CLEAR_ROSTER_MODAL';
export const CLEAR_ROSTER_SUCCESS_MODAL = 'CLEAR_ROSTER_SUCCESS_MODAL';
export const CATCH_ALL_CLASS_MODAL = 'CATCH_ALL_CLASS_MODAL';

export const DEACTIVATE_CLASS_MODAL = 'DEACTIVATE_CLASS_MODAL';
export const DEACTIVATE_CLASS_SUCCESS_MODAL = 'DEACTIVATE_CLASS_SUCCESS_MODAL';
export const DEACTIVATE_GROUP_MODAL = 'DEACTIVATE_GROUP_MODAL';
export const DEACTIVATE_GROUP_SUCCESS_MODAL = 'DEACTIVATE_GROUP_SUCCESS_MODAL';
export const DEACTIVATE_QUIZ_MODAL = 'DEACTIVATE_QUIZ_MODAL';
export const DEACTIVATE_SCHOOL_MODAL = 'DEACTIVATE_SCHOOL_MODAL';
export const DEACTIVATE_SCHOOL_SUCCESS_MODAL = 'DEACTIVATE_SCHOOL_SUCCESS_MODAL';
export const DEACTIVATE_STUDENT_MODAL = 'DEACTIVATE_STUDENT_MODAL';
export const DEACTIVATE_STUDENT_SUCCESS_MODAL = 'DEACTIVATE_STUDENT_SUCCESS_MODAL';
export const DEACTIVATE_USER_MODAL = 'DEACTIVATE_USER_MODAL';
export const DEACTIVATE_USER_SUCCESS_MODAL = 'DEACTIVATE_USER_SUCCESS_MODAL';
export const DELETE_INACTIVE_SUCCESS_MODAL = 'DELETE_INACTIVE_SUCCESS_MODAL';

export const EDIT_ADMIN_MODAL = 'EDIT_ADMIN_MODAL';
export const EDIT_ADMIN_MODAL_WARNING = 'EDIT_ADMIN_MODAL_WARNING';
export const EDIT_DISTRICT_PROFILE = 'EDIT_DISTRICT_PROFILE';
export const EDIT_QUIZ_COLLECTION_NAMES_MODAL = 'EDIT_QUIZ_COLLECTION_NAMES_MODAL';

export const HANDLE_EXPORT_TEACHER_QUIZ_MODAL = 'HANDLE_EXPORT_TEACHER_QUIZ_MODAL';

export const IREAD_MODAL = 'IREAD_MODAL';
export const IREAD_SCREENER_MODAL = 'IREAD_SCREENER_MODAL';
export const IREAD_ADD_MODAL = 'IREAD_ADD_MODAL';

export const LOGOUT_MODAL = 'LOGOUT_MODAL';

export const MESSAGE_LOG_MODAL = 'MESSAGE_LOG_MODAL';

export const NO_ITEMS_SELECTED_MODAL = 'NO_ITEMS_SELECTED_MODAL';

export const OK_CANCEL_MODAL = 'OK_CANCEL_MODAL';

export const PRINT_BOOK_LABEL_MODAL = 'PRINT_BOOK_LABEL_MODAL';
export const PRINT_CUSTOM_QUIZ_MODAL = 'PRINT_CUSTOM_QUIZ_MODAL';
export const PRINT_INBOX_PROGRAM = 'PRINT_INBOX_PROGRAM';
export const PRINT_QUIZ_AND_ANSWER_KEY_MODAL = 'PRINT_QUIZ_AND_ANSWER_KEY_MODAL';
export const PROGRAM_SETTING_SET_STUDENT_LEVEL_MODAL = 'PROGRAM_SETTING_SET_STUDENT_LEVEL_MODAL';

export const R180NG_SKIP_SEGMENT_MODAL = 'R180NG_SKIP_SEGMENT_MODAL';
export const R180NG_TOPICS_SKIP_MODAL = 'R180NG_TOPICS_SKIP_MODAL';
export const READ_180_NG_ASSAIGNMENT_MODAL = 'READ_180_NG_ASSAIGNMENT_MODAL';
export const READ_180_RESPOND_WRITE_MODAL = 'READ_180_RESPOND_WRITE_MODAL';
export const MIA_REACTIVATE_SCHOOL_MODAL = 'MIA_REACTIVATE_SCHOOL_MODAL';
export const MIA_REACTIVATE_CLASS_MODAL = 'MIA_REACTIVATE_CLASS_MODAL';
export const R180NG_TOPICS_STAGE_MODAL = 'R180NG_TOPICS_STAGE_MODAL';
export const REMOVE_ADMIN_MODAL = 'REMOVE_ADMIN_MODAL';
export const RSKILLSCC_TEST_ASSIGNMENT_SAVE_SUCCESS_MODAL =
  'RSKILLSCC_TEST_ASSIGNMENT_SAVE_SUCCESS_MODAL';

export const SCHOOL_FORM_MODAL = 'SCHOOL_FORM_MODAL';
export const SEARCH_CLASS_ASSIGN_MODAL = 'SEARCH_CLASS_ASSIGN_MODAL';
export const SEARCH_MODAL = 'SEARCH_MODAL';
export const SEARCH_RESULT_DETAILS_MODAL = 'SEARCH_RESULT_DETAILS_MODAL';
export const STUDENT_FORM_MODAL = 'STUDENT_FORM_MODAL';
export const TEACHER_FORM_MODAL = 'TEACHER_FORM_MODAL';
export const TEACHER_MADE_QUIZ_MODAL = 'TEACHER_MADE_QUIZ_MODAL';
export const WARNING_MODAL = 'WARNING_MODAL';
export const READ_180_MODAL = 'READ_180_MODAL';
export const SYSTEM_44_STUDENT_GOALS_MODAL = 'SYSTEM_44_STUDENT_GOALS_MODAL';
export const SYSTEM_44_SUCCESS_RECORD_MODAL = 'SYSTEM_44_SUCCESS_RECORD_MODAL';
export const IREAD_STUDENT_WORK_MODAL = 'IREAD_STUDENT_WORK_MODAL';

export const XSKILLS_TEST_ASSIGNMENT_SAVE_SUCCESS_MODAL =
  'XSKILLS_TEST_ASSIGNMENT_SAVE_SUCCESS_MODAL';
