/*
 *
 * PSSettingContainer constants
 *
 */

export const PS_SETTINGS_CONTAINER = 'app/PSSettingContainer/PS_SETTINGS_CONTAINER';
export const PS_SETTINGS_CONTAINER_SUCCESS = 'app/PSSettingContainer/PS_SETTINGS_CONTAINER_SUCCESS';
export const PS_SETTINGS_CONTAINER_FAILURE = 'app/PSSettingContainer/PS_SETTINGS_CONTAINER_FAILURE';

export const PS_SETTINGS_SAVE = 'app/PSSettingContainer/PS_SETTINGS_SAVE';
export const PS_SETTINGS_SAVE_SUCCESS = 'app/PSSettingContainer/PS_SETTINGS_SAVE_SUCCESS';
export const PS_SETTINGS_SAVE_FAILURE = 'app/PSSettingContainer/PS_SETTINGS_SAVE_FAILURE';

export const PS_TEST_ASSIGNMENT = 'app/PSSettingContainer/PS_TEST_ASSIGNMENT';
export const PS_TEST_ASSIGNMENT_SUCCESS = 'app/PSSettingContainer/PS_TEST_ASSIGNMENT_SUCCESS';
export const PS_TEST_ASSIGNMENT_FAILURE = 'app/PSSettingContainer/PS_TEST_ASSIGNMENT_FAILURE';

export const PS_TEST_ASSIGNMENT_TEST_REQUEST =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_TEST_REQUEST';
export const PS_TEST_ASSIGNMENT_TEST_SUCCESS =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_TEST_SUCCESS';
export const PS_TEST_ASSIGNMENT_TEST_FAILURE =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_TEST_FAILURE';

export const PS_TEST_ASSIGNMENT_SUBPRODUCT_REQUEST =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_SUBPRODUCT_REQUEST';
export const PS_TEST_ASSIGNMENT_SUBPRODUCT_SUCCESS =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_SUBPRODUCT_SUCCESS';
export const PS_TEST_ASSIGNMENT_SUBPRODUCT_FAILURE =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_SUBPRODUCT_FAILURE';

export const PS_TEST_ASSIGNMENT_MODULE_REQUEST =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_MODULE_REQUEST';
export const PS_TEST_ASSIGNMENT_MODULE_SUCCESS =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_MODULE_SUCCESS';
export const PS_TEST_ASSIGNMENT_MODULE_FAILURE =
  'app/PSSettingContainer/PS_TEST_ASSIGNMENT_MODULE_FAILURE';

export const URL = 'dtm/DTMProductControls';
