/*
 *
 * IreadSettingsContainer constants
 *
 */

export const IREAD_PROGRAM_SETTINGS_REQUEST = 'IREAD_PROGRAM_SETTINGS_REQUEST';
export const IREAD_PROGRAM_SETTINGS_REQUEST_SUCCESS = 'IREAD_PROGRAM_SETTINGS_REQUEST_SUCCESS';
export const IREAD_PROGRAM_SETTINGS_REQUEST_FAILURE = 'IREAD_PROGRAM_SETTINGS_REQUEST_FAILURE';

export const IREAD_SAVE_REQUEST = 'IREAD_SAVE_REQUEST';
export const IREAD_SAVE_REQUEST_SUCCESS = 'IREAD_SAVE_REQUEST_SUCCESS';
export const IREAD_SAVE_REQUEST_FAILURE = 'IREAD_SAVE_REQUEST_FAILURE';

export const IREAD_SETTINGS_URL = '/iRead/s44jrProductCtrls';
