/*
 *
 * AddEditTeacher constants
 *
 */

export const FORM_TEACHER_PROFILE = 'form_teacher_profile';

export const ADD_EDIT_TEACHER_REQUEST = 'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST';
export const ADD_EDIT_TEACHER_REQUEST_SUCCESS =
  'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST_SUCCESS';
export const ADD_EDIT_TEACHER_REQUEST_FAILURE =
  'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST_FAILURE';

export const POST_ADD_TEACHER_REQUEST = 'app/AddEditTeacher/POST_ADD_TEACHER_REQUEST';
export const POST_ADD_TEACHER_REQUEST_SUCCESS =
  'app/AddEditTeacher/POST_ADD_TEACHER_REQUEST_SUCCESS';
export const POST_ADD_TEACHER_REQUEST_FAILURE =
  'app/AddEditTeacher/POST_ADD_TEACHER_REQUEST_FAILURE';

export const POST_SAVE_TEACHER_REQUEST = 'app/AddEditTeacher/POST_SAVE_TEACHER_REQUEST';
export const POST_SAVE_TEACHER_REQUEST_SUCCESS =
  'app/AddEditTeacher/POST_SAVE_TEACHER_REQUEST_SUCCESS';
export const POST_SAVE_TEACHER_REQUEST_FAILURE =
  'app/AddEditTeacher/POST_SAVE_TEACHER_REQUEST_FAILURE';

export const POST_SAVE_TEACHER_MIA_REQUEST = 'app/AddEditTeacher/POST_SAVE_TEACHER_MIA_REQUEST';

export const ADD_EDIT_TEACHER_REQUEST_PROFILE_DETAILS_SUCCESS =
  'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST_PROFILE_DETAILS_SUCCESS';
export const ADD_EDIT_TEACHER_REQUEST_PERMISSIONS_SUCCESS =
  'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST_PERMISSIONS_SUCCESS';
export const ADD_EDIT_TEACHER_REQUEST_SCHOOL_AND_CLASSES_SUCCESS =
  'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST_SCHOOL_AND_CLASSES_SUCCESS';
export const ADD_EDIT_TEACHER_REQUEST_PASSWORD_CONFIG_SUCCESS =
  'app/AddEditTeacher/ADD_EDIT_TEACHER_REQUEST_PASSWORD_CONFIG_SUCCESS';
