/*
 *
 * InboxContainer constants
 *
 */

export const GET_INBOX_CLASS_TREELIST = 'app/InboxContainer/GET_INBOX_CLASS_TREELIST';
export const SET_INBOX_CLASS_TREELIST = 'app/InboxContainer/SET_INBOX_CLASS_TREELIST';
export const GET_STUDENT_SUBMISSION_META_DATA =
  'app/InboxContainer/GET_STUDENT_SUBMISSION_META_DATA';
export const GET_PORTFOLIO_STUDENT_ENROLMENT_TREE_DATA =
  'app/InboxContainer/GET_PORTFOLIO_STUDENT_ENROLMENT_TREE_DATA';
export const SET_STUDENT_SUBMISSION_META_DATA =
  'app/InboxContainer/SET_STUDENT_SUBMISSION_META_DATA';
export const GET_STUDENT_LIST_CLASS = 'app/InboxContainer/GET_STUDENT_LIST_CLASS';
export const GET_ASSIGNMENT_LIST_CLASS = 'app/InboxContainer/GET_ASSIGNMENT_LIST_CLASS';
export const SET_TEMP_GRIDDATA = 'app/InboxContainer/SET_TEMP_GRIDDATA';
export const SET_TEMP_GRIDDATA_WITH_TREE = 'app/InboxContainer/SET_TEMP_GRIDDATA_WITH_TREE';
export const SET_ASSIGNMENT_LIST_AND_TREE = 'app/InboxContainer/SET_ASSIGNMENT_LIST_AND_TREE';
