export const mockPermissions = [
  { id: ['100'], name: ['Edit Student Profile'], display_name: ['Edit Student Profile'] },
  { id: ['1000'], name: ['View Demographics'], display_name: ['View Demographics'] },
  { id: ['110'], name: ['View Student Profile'], display_name: ['View Student Profile'] },
  { id: ['1100'], name: ['Export Data'], display_name: ['Export Data'] },
  {
    id: ['1500'],
    name: ['Manage Student Applications Settings'],
    display_name: ['Manage Student Applications Settings'],
  },
  {
    id: ['1550'],
    name: ['Manage Student Enrollment'],
    display_name: ['Manage Student Enrollment'],
  },
  { id: ['1600'], name: ['NCLB Filter on Reports'], display_name: ['NCLB Filter on Reports'] },
  {
    id: ['1700'],
    name: ['Subgroup Setup in District and School'],
    display_name: ['Subgroup Setup in District and School'],
  },
  { id: ['1800'], name: ['License Key Input'], display_name: ['License Key Input'] },
  { id: ['200'], name: ['Edit Group Profile'], display_name: ['Edit Group Profile'] },
  { id: ['210'], name: ['View Group Profile'], display_name: ['View Group Profile'] },
  { id: ['300'], name: ['Edit Class Profile'], display_name: ['Edit Class Profile'] },
  { id: ['310'], name: ['View Class Profile'], display_name: ['View Class Profile'] },
  { id: ['400'], name: ['Edit School Profile'], display_name: ['Edit School Profile'] },
  { id: ['410'], name: ['View School Profile'], display_name: ['View School Profile'] },
  { id: ['500'], name: ['Edit District Profile'], display_name: ['Edit District Profile'] },
  { id: ['510'], name: ['View District Profile'], display_name: ['View District Profile'] },
  { id: ['600'], name: ['Edit Teacher Profile'], display_name: ['Edit Teacher Profile'] },
  { id: ['610'], name: ['View Teacher Profile'], display_name: ['View Teacher Profile'] },
  { id: ['620'], name: ['View Own Profile'], display_name: ['View Own Profile'] },
  { id: ['630'], name: ['Edit Own Profile'], display_name: ['Edit Own Profile'] },
  { id: ['640'], name: ['View Own Permissions'], display_name: ['View Own Permissions'] },
  { id: ['660'], name: ['View Others Permissions'], display_name: ['View Others Permissions'] },
  { id: ['670'], name: ['Edit Others Permissions'], display_name: ['Edit Other Permissions'] },
  { id: ['700'], name: ['Manage Inactive Accounts'], display_name: ['Manage Inactive Accounts'] },
  { id: ['820'], name: ['Add Students'], display_name: ['Add Students'] },
  { id: ['825'], name: ['Add Groups'], display_name: ['Add Groups'] },
  { id: ['830'], name: ['Add Classes'], display_name: ['Add Classes'] },
  { id: ['835'], name: ['Add Teachers'], display_name: ['Add Teachers'] },
  { id: ['840'], name: ['Add Schools'], display_name: ['Add Schools'] },
  { id: ['845'], name: ['Deactivate Student'], display_name: ['Deactivate Student'] },
  { id: ['850'], name: ['Deactivate Group'], display_name: ['Deactivate Group'] },
  { id: ['855'], name: ['Deactivate Class'], display_name: ['Deactivate Class'] },
  { id: ['860'], name: ['Deactivate Teacher'], display_name: ['Deactivate Teacher'] },
  { id: ['865'], name: ['Deactivate School'], display_name: ['Deactivate School'] },
  { id: ['900'], name: ['Import Student Rosters'], display_name: ['Import Student Rosters'] },
];
