/*
 *
 * XSkillsSettingContainer constants
 *
 */

export const XSKILLS_SETTING_CONTAINER_REQUEST =
  'app/XSkillsSettingContainer/XSKILLS_SETTING_CONTAINER_REQUEST';

export const XSKILLS_SETTING_CONTAINER_REQUEST_FAILURE =
  'app/XSkillsSettingContainer/XSKILLS_SETTING_CONTAINER_REQUEST_FAILURE';

export const XSKILLS_SETTING_CONTAINER_REQUEST_SUCCESS =
  'app/XSkillsSettingContainer/XSKILLS_SETTING_CONTAINER_REQUEST_SUCCESS';

export const XSKILLS_SETTINGS_GET_COMMAND = 'get_xskills_settings';

export const XSKILLS_SETTINGS_LOADING = 'app/XSkillsSettingContainer/XSKILLS_SETTINGS_LOADING';

export const XSKILLS_SETTINGS_REQUEST = 'app/XSkillsSettingContainer/XSKILLS_SETTINGS_REQUEST';

export const XSKILLS_SETTINGS_REQUEST_FAILURE =
  'app/XSkillsSettingContainer/XSKILLS_SETTINGS_REQUEST_FAILURE';

export const XSKILLS_SETTINGS_REQUEST_SUCCESS =
  'app/XSkillsSettingContainer/XSKILLS_SETTINGS_REQUEST_SUCCESS';

export const XSKILLS_SETTINGS_SAVE_REQUEST =
  'app/XSkillsSettingContainer/XSKILLS_SETTINGS_SAVE_REQUEST';

export const XSKILLS_SETTINGS_URL = '/xSkills/XTProductCtrls';

export const XSKILLS_TEST_ASSIGN_URL = '/xSkills/XTProductCtrls';

export const XSKILLS_TEST_ASSIGN_GET_COMMAND = 'get_xskills_tests';

export const XSKILLS_TEST_ASSIGN_SET_COMMAND = 'set_xskills_current_test';

export const XSKILLS_TEST_ASSIGNMENT_LOADING = 'XSKILLS_TEST_ASSIGNMENT_LOADING';

export const XSKILLS_TEST_ASSIGNMENT_REQUEST = 'XSKILLS_TEST_ASSIGNMENT_REQUEST';

export const XSKILLS_TEST_ASSIGNMENT_REQUEST_SUCCESS = 'XSKILLS_TEST_ASSIGNMENT_REQUEST_SUCCESS';

export const XSKILLS_TEST_ASSIGNMENT_REQUEST_FAILURE = 'XSKILLS_TEST_ASSIGNMENT_REQUEST_FAILURE';

export const XSKILLS_TEST_ASSIGNMENT_SAVE_REQUEST = 'XSKILLS_TEST_ASSIGNMENT_SAVE_REQUEST';

export const XSKILLS_TEST_ASSIGNMENT_SAVE_REQUEST_SUCCESS =
  'XSKILLS_TEST_ASSIGNMENT_SAVE_REQUEST_SUCCESS';

export const XSKILLS_TEST_ASSIGNMENT_SAVE_REQUEST_FAILURE =
  'XSKILLS_TEST_ASSIGNMENT_SAVE_REQUEST_FAILURE';
