const PDFSort = {
  district: {
    dtm_04: '',
    fad_05: '',
    fad_09:
      '?sortOnElement=school&sortByElement=sequence_id&sortOrder=asc&usageType=program_completed',
    fm_06: '',
    fm_13: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    fm_05: '?sortOnElement=grade&sortByElement=name&operation=null&sortOrder=asc',
    fmng_09: '?sortOnElement=demographic&sortByElement=name&sortOrder=asc',
    fmng_13: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    fmng_06: '',
    fmng_05: '?sortOnElement=grade&sortByElement=name&operation=null&sortOrder=asc',
    m180_01: '',
    m180_y2_01: '',
    r180_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_04: '?sortOnElement=NA&sortByElement=first_column&sortOrder=asc',
    r180_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_33: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    r180_28: '',
    r180_27: '',
    r180ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_04: '?sortOnElement=NA&sortByElement=first_column&sortOrder=asc',
    r180ng_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_33: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    r180ng_28: '',
    r180ng_27: '',
    rt_02: '',
    rt_01: '',
    rtng_01: '',
    s44_06: '',
    s44jr_02: '',
    s44ng_06: '',
    s44ng_08: '',
    math_inventory_12: '?sortOnElement=school&sortByElement=grade_sort&sortOrder=asc',
    math_inventory_13: '?sortOnElement=undefined&sortByElement=undefined&sortOrder=undefined',
    math_inventory_02: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    phonics_inventory_04: '',
    phonics_inventory_05: '',
    reading_counts_10: '?sortOnElement=book&sortByElement=rank&sortOrder=asc',
    reading_counts_01: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    reading_counts_02: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    reading_counts_21: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    reading_inventory_05:
      '?sortOnElement=subgroup&sortByElement=name&cohort=district&sortOrder=asc',
    reading_inventory_03:
      '?sortOnElement=subgroup&sortByElement=name&cohort=district&sortOrder=asc',
    reading_inventory_01:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=district&sortOrder=asc',
    reading_inventory_21: '',
    reading_inventory_04:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=district&sortOrder=asc',
    reading_inventory_02: '',
    reading_inventory_07: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    reading_inventory_06: '?sortOnElement=school&sortByElement=name&sortOrder=asc',
    xt_02:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=I&testId=undefined&sortOrder=asc',
    xt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
  },
  school: {
    dtm_04: '',
    fad_05: '',
    fad_09:
      '?sortOnElement=grade&sortByElement=sequence_id&sortOrder=asc&usageType=program_completed',
    fm_06: '',
    fm_13: '?sortOnElement=class&sortByElement=name&sortOrder=asc',
    fm_05: '?sortOnElement=grade&sortByElement=name&operation=null&sortOrder=asc',
    fmng_09: '?sortOnElement=demographic&sortByElement=name&sortOrder=asc',
    fmng_13: '?sortOnElement=class&sortByElement=name&sortOrder=asc',
    fmng_06: '',
    fmng_05: '?sortOnElement=grade&sortByElement=name&operation=null&sortOrder=asc',
    m180_01: '',
    m180_y2_01: '',
    r180_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_04: '?sortOnElement=NA&sortByElement=first_column&sortOrder=asc',
    r180_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_33: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    r180_28: '',
    r180_27: '',
    r180ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_04: '?sortOnElement=NA&sortByElement=first_column&sortOrder=asc',
    r180ng_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_33: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    r180ng_28: '',
    r180ng_27: '',
    rt_02:
      '?sortOnElement=strand&sortByElement=desc&rstLevel=a&testBundleId=rSkills_Tests&stageLevel=A&sortOrder=asc',
    rt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    rtng_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    s44_06: '',
    s44jr_02: '',
    s44jr_01: '',
    s44ng_06: '',
    s44ng_08: '',
    math_inventory_12: '?sortOnElement=grade&sortByElement=grade_sort&sortOrder=asc',
    math_inventory_13: '',
    math_inventory_02: '?sortOnElement=grade&sortByElement=grade_sort&sortOrder=asc',
    phonics_inventory_05: '',
    phonics_inventory_04: '',
    reading_counts_10: '?sortOnElement=book&sortByElement=rank&sortOrder=asc',
    reading_counts_01: '?sortOnElement=grade&sortByElement=name&sortOrder=asc',
    reading_counts_11:
      '?sortOnElement=student&sortByElement=undefined&quizName=undefined&sortOrder=undefined',
    reading_counts_02: '?sortOnElement=grade&sortByElement=name&sortOrder=asc',
    reading_counts_21: '?sortOnElement=grade&sortByElement=name&sortOrder=asc',
    reading_counts_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_05: '?sortOnElement=subgroup&sortByElement=name&cohort=school&sortOrder=asc',
    reading_inventory_03: '?sortOnElement=subgroup&sortByElement=name&cohort=school&sortOrder=asc',
    reading_inventory_01:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=school&sortOrder=asc',
    reading_inventory_21: '',
    reading_inventory_04:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=school&sortOrder=asc',
    reading_inventory_02: '',
    reading_inventory_07: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    reading_inventory_06: '?sortOnElement=grade&sortByElement=name&sortOrder=asc',
    xt_02:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=undefined&testId=undefined&sortOrder=asc',
    xt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
  },
  grade: {
    dtm_02: '?sortOnElement=undefined&sortByElement=undefined&sortOrder=undefined',
    fad_05: '',
    fad_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    fm_06: '',
    fm_07: '',
    fm_02: '?sortOnElement=student&sortByElement=undefined&sortOrder=undefined',
    fm_05: '?sortOnElement=class&sortByElement=name&operation=null&sortOrder=asc',
    fmng_09: '?sortOnElement=demographic&sortByElement=name&sortOrder=asc',
    fmng_06: '',
    fmng_07: '',
    fmng_02: '?sortOnElement=student&sortByElement=undefined&sortOrder=undefined',
    fmng_05: '?sortOnElement=class&sortByElement=name&operation=null&sortOrder=asc',
    r180_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_11: '',
    r180_04: '?sortOnElement=NA&sortByElement=first_column&sortOrder=asc',
    r180_13: '?sortOnElement=student&sortByElement=level&sortOrder=asc',
    r180_31tch: '',
    r180_31eng: '',
    r180_31hcr: '',
    r180_31hmo: '',
    r180_31spa: '',
    r180_31vie: '',
    r180_32tch: '',
    r180_32eng: '',
    r180_32hcr: '',
    r180_32hmo: '',
    r180_32spa: '',
    r180_32vie: '',
    r180_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_19: '',
    r180_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_28: '',
    r180_27: '',
    r180ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180ng_04: '?sortOnElement=NA&sortByElement=first_column&sortOrder=asc',
    r180ng_13: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_31tch: '',
    r180ng_31eng: '',
    r180ng_31hcr: '',
    r180ng_31hmo: '',
    r180ng_31spa: '',
    r180ng_31vie: '',
    r180ng_32tch: '',
    r180ng_32eng: '',
    r180ng_32hcr: '',
    r180ng_32hmo: '',
    r180ng_32spa: '',
    r180ng_32vie: '',
    r180ng_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_19: '',
    r180ng_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180ng_28: '',
    r180ng_27: '',
    rt_05: '',
    rt_04: '',
    rt_06: '',
    rt_02:
      '?sortOnElement=strand&sortByElement=desc&rstLevel=a&testBundleId=rSkills_Tests&stageLevel=A&sortOrder=asc',
    rt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    rtng_08: '',
    rtng_05: '',
    rtng_04: '',
    rtng_06: '',
    rtng_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    s44_04:
      '?sortOnElement0=nodata&sortByElement0=nodata&sortOrder0=nodata&sortOnElement1=nodata&sortByElement1=nodata&sortOrder1=nodata&sortOnElement2=nodata&sortByElement2=nodata&sortOrder2=nodata&sortOnElement3=nodata&sortByElement3=nodata&sortOrder3=nodata&sortOnElement4=nodata&sortByElement4=nodata&sortOrder4=nodata&sortOnElement5=nodata&sortByElement5=nodata&sortOrder5=nodata',
    s44_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_09: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    math_inventory_04: '?sortOnElement=student&sortByElement=quantile_growth_sort&sortOrder=desc',
    math_inventory_03:
      '?sortOnElement=student&sortByElement=quantile_sort&sortOrder=undefined&cohort=grade',
    math_inventory_13: '',
    math_inventory_08: '?sortOnElement=undefined&sortByElement=undefined&sortOrder=undefined',
    math_inventory_02: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    phonics_inventory_05: '',
    phonics_inventory_04: '',
    phonics_inventory_01: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    phonics_inventory_03: '',
    phonics_inventory_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc&testNumber=none',
    reading_counts_08:
      '?sortOnElement=student&sortByElement=undefined&awardLevel=undefined&awardType=undefined&sortOrder=undefined',
    reading_counts_17eng: '',
    reading_counts_17spa: '',
    reading_counts_18eng: '',
    reading_counts_18spa: '',
    reading_counts_19eng: '',
    reading_counts_19spa: '',
    reading_counts_20: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_21: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    reading_counts_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_16: '',
    reading_counts_04: '',
    reading_counts_06: '',
    reading_counts_15: '',
    reading_inventory_05: '?sortOnElement=subgroup&sortByElement=name&cohort=grade&sortOrder=asc',
    reading_inventory_03: '?sortOnElement=subgroup&sortByElement=name&cohort=grade&sortOrder=asc',
    reading_inventory_01:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=grade&individualName=Grade%206&sortOrder=asc',
    reading_inventory_27: '',
    reading_inventory_09: '?sortOnElement=student&sortByElement=growth&sortOrder=desc',
    reading_inventory_13: '?sortOnElement=student&sortByElement=performance_standard&sortOrder=asc',
    reading_inventory_19eng: '',
    reading_inventory_19spa: '',
    reading_inventory_20eng: '',
    reading_inventory_20spa: '',
    reading_inventory_04:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=grade&sortOrder=asc',
    reading_inventory_02: '',
    reading_inventory_23: '',
    reading_inventory_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_18: '',
    reading_inventory_14: '?sortOnElement=test&sortByElement=undefined&sortOrder=undefined',
    reading_inventory_15: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_07: '?sortOnElement=teacher&sortByElement=name&sortOrder=asc',
    xt_03:
      '?sortOnElement=student&sortByElement=name&responseId=undefined&sortOrder=undefined&courseLevel=undefined',
    xt_02:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=undefined&testId=undefined&sortOrder=asc',
    xt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
  },
  teacher: {
    dtm_02: '?sortOnElement=undefined&sortByElement=undefined&sortOrder=undefined',
    fad_03: '?sortOnElement=student&sortByElement=name&sortOrder=asc&type=placement_assessment',
    fad_01: '?sortOnElement=student&sortByElement=current_lesson&sortOrder=asc',
    fad_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    fm_06: '',
    fm_07: '',
    fm_02: '?sortOnElement=student&sortByElement=undefined&sortOrder=undefined',
    fm_01: '',
    fm_04: '',
    fm_03: '',
    fmng_07: '',
    fmng_02: '?sortOnElement=student&sortByElement=undefined&sortOrder=undefined',
    fmng_01: '',
    fmng_04: '',
    fmng_03: '',
    r180_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_20: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180_13: '?sortOnElement=student&sortByElement=level&sortOrder=asc',
    r180_31tch: '',
    r180_31eng: '',
    r180_31hcr: '',
    r180_31hmo: '',
    r180_31spa: '',
    r180_31vie: '',
    r180_32tch: '',
    r180_32eng: '',
    r180_32hcr: '',
    r180_32hmo: '',
    r180_32spa: '',
    r180_32vie: '',
    r180_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_19: '',
    r180_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_10: '',
    r180_28: '',
    r180_27: '',
    r180ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180ng_13: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_31tch: '',
    r180ng_31eng: '',
    r180ng_31hcr: '',
    r180ng_31hmo: '',
    r180ng_31spa: '',
    r180ng_31vie: '',
    r180ng_32tch: '',
    r180ng_32eng: '',
    r180ng_32hcr: '',
    r180ng_32hmo: '',
    r180ng_32spa: '',
    r180ng_32vie: '',
    r180ng_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_19: '',
    r180ng_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_18: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_10: '',
    r180ng_28: '',
    r180ng_27: '',
    rt_05: '',
    rt_04: '',
    rt_06: '',
    rt_02:
      '?sortOnElement=strand&sortByElement=desc&rstLevel=a&testBundleId=rSkills_Tests&stageLevel=A&sortOrder=asc',
    rt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    rtng_08: '',
    rtng_05: '',
    rtng_04: '',
    rtng_06: '',
    rtng_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    s44_04:
      '?sortOnElement0=student&sortByElement0=name&sortOrder0=asc&sortOnElement1=nodata&sortByElement1=nodata&sortOrder1=nodata&sortOnElement2=nodata&sortByElement2=nodata&sortOrder2=nodata&sortOnElement3=nodata&sortByElement3=nodata&sortOrder3=nodata&sortOnElement4=nodata&sortByElement4=nodata&sortOrder4=nodata&sortOnElement5=student&sortByElement5=name&sortOrder5=asc',
    s44_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_09: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    math_inventory_04: '?sortOnElement=student&sortByElement=quantile_growth_sort&sortOrder=desc',
    math_inventory_10: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    math_inventory_13: '',
    math_inventory_08: '?sortOnElement=undefined&sortByElement=undefined&sortOrder=undefined',
    math_inventory_09eng: '',
    math_inventory_09spa: '',
    math_inventory_02: '?sortOnElement=class&sortByElement=name&sortOrder=asc',
    phonics_inventory_05: '',
    phonics_inventory_04: '',
    phonics_inventory_01:
      '?sortOnElement=student&sortByElement=name&sortOrder=asc&testNumber=undefined',
    phonics_inventory_03: '',
    phonics_inventory_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_08:
      '?sortOnElement=student&sortByElement=name&awardLevel=Blue&awardType=Points&sortOrder=asc',
    reading_counts_10: '?sortOnElement=book&sortByElement=rank&sortOrder=asc',
    reading_counts_01: '?sortOnElement=class&sortByElement=name&sortOrder=asc',
    reading_counts_03: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_11:
      '?sortOnElement=student&sortByElement=name&quizName=%22A%22%20Is%20for%20Abigail&sortOrder=asc',
    reading_counts_17eng: '',
    reading_counts_17spa: '',
    reading_counts_18eng: '',
    reading_counts_18spa: '',
    reading_counts_19eng: '',
    reading_counts_19spa: '',
    reading_counts_20: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_21: '?sortOnElement=class&sortByElement=name&sortOrder=asc',
    reading_counts_14: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    reading_counts_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_16: '',
    reading_counts_04: '',
    reading_counts_06: '',
    reading_counts_15: '',
    reading_inventory_01:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=teacher&sortOrder=asc',
    reading_inventory_26: '',
    reading_inventory_27: '',
    reading_inventory_25: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_09: '?sortOnElement=student&sortByElement=growth&sortOrder=desc',
    reading_inventory_13: '?sortOnElement=student&sortByElement=performance_standard&sortOrder=asc',
    reading_inventory_19eng: '',
    reading_inventory_19spa: '',
    reading_inventory_20eng: '',
    reading_inventory_20spa: '',
    reading_inventory_04:
      '?sortOnElement=performance_standard&sortByElement=id&cohort=teacher&sortOrder=asc',
    reading_inventory_10:
      '?sortOnElement=performance_standard&sortByElement=id&individualName=K&sortOrder=asc',
    reading_inventory_02: '',
    reading_inventory_23: '',
    reading_inventory_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_18: '',
    reading_inventory_14: '?sortOnElement=test&sortByElement=undefined&sortOrder=undefined',
    reading_inventory_15: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_07: '',
    reading_inventory_12: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    xt_03: '',
    xt_05: '',
    xt_04: '?sortOnElement=skill&sortByElement=undefined&sortOrder=undefined',
    xt_06: '',
    xt_02:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=I&testId=undefined&sortOrder=asc',
    xt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
  },
  class: {
    r180_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_20: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180_13: '?sortOnElement=student&sortByElement=level&sortOrder=asc',
    r180_31tch: '',
    r180_31eng: '',
    r180_31hcr: '',
    r180_31hmo: '',
    r180_31spa: '',
    r180_31vie: '',
    r180_32tch: '',
    r180_32eng: '',
    r180_32hcr: '',
    r180_32hmo: '',
    r180_32spa: '',
    r180_32vie: '',
    r180_19: '',
    r180_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_23: '',
    r180_10: '',
    r180_09: '',
    r180_28: '',
    r180_27: '',
    r180ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_20: '?sortOnElement=undefined&sortByElement=undefined&sortOrder=undefined',
    r180ng_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180ng_13: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_31tch: '',
    r180ng_31eng: '',
    r180ng_31hcr: '',
    r180ng_31hmo: '',
    r180ng_31spa: '',
    r180ng_31vie: '',
    r180ng_32tch: '',
    r180ng_32eng: '',
    r180ng_32hcr: '',
    r180ng_32hmo: '',
    r180ng_32spa: '',
    r180ng_32vie: '',
    r180ng_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_19: '',
    r180ng_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180ng_23: '',
    r180ng_10: '',
    r180ng_09: '',
    r180ng_28: '',
    r180ng_27: '',
    rt_05: '',
    rt_04: '',
    rt_06: '',
    rt_02:
      '?sortOnElement=strand&sortByElement=desc&rstLevel=a&testBundleId=rSkills_Tests&stageLevel=A&sortOrder=asc',
    rt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    rtng_08: '',
    rtng_07: '',
    rtng_05: '',
    rtng_04: '',
    rtng_06: '',
    rtng_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    s44_04:
      '?sortOnElement0=student&sortByElement0=name&sortOrder0=asc&sortOnElement1=nodata&sortByElement1=nodata&sortOrder1=nodata&sortOnElement2=nodata&sortByElement2=nodata&sortOrder2=nodata&sortOnElement3=nodata&sortByElement3=nodata&sortOrder3=nodata&sortOnElement4=nodata&sortByElement4=nodata&sortOrder4=nodata&sortOnElement5=nodata&sortByElement5=nodata&sortOrder5=nodata',
    s44_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_09: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    phonics_inventory_01: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    phonics_inventory_03: '',
    phonics_inventory_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc&testNumber=none',
    reading_counts_08:
      '?sortOnElement=student&sortByElement=name&awardLevel=Blue&awardType=Points&sortOrder=asc',
    reading_counts_10: '?sortOnElement=book&sortByElement=rank&sortOrder=asc',
    reading_counts_03: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_01: '?sortOnElement=group&sortByElement=name&sortOrder=asc',
    reading_counts_11:
      '?sortOnElement=student&sortByElement=undefined&quizName=undefined&sortOrder=undefined',
    reading_counts_17eng: '',
    reading_counts_17spa: '',
    reading_counts_18eng: '',
    reading_counts_18spa: '',
    reading_counts_19eng: '',
    reading_counts_19spa: '',
    reading_counts_20: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_21: '?sortOnElement=group&sortByElement=name&sortOrder=asc',
    reading_counts_09: '?sortOnElement=student&sortByElement=undefined&sortOrder=undefined',
    reading_counts_14: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    reading_counts_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_16: '',
    reading_counts_04: '',
    reading_counts_06: '',
    reading_counts_15: '',
    reading_inventory_26: '',
    reading_inventory_27: '',
    reading_inventory_25: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_09: '?sortOnElement=student&sortByElement=growth&sortOrder=desc',
    reading_inventory_13: '?sortOnElement=student&sortByElement=performance_standard&sortOrder=asc',
    reading_inventory_19eng: '',
    reading_inventory_19spa: '',
    reading_inventory_20eng: '',
    reading_inventory_20spa: '',
    reading_inventory_10:
      '?sortOnElement=performance_standard&sortByElement=id&individualName=K&sortOrder=asc',
    reading_inventory_02: '',
    reading_inventory_23: '',
    reading_inventory_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_18: '',
    reading_inventory_14: '?sortOnElement=test&sortByElement=undefined&sortOrder=undefined',
    reading_inventory_15: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_22: '',
    reading_inventory_12: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    xt_03: '',
    xt_05: '',
    xt_04: '?sortOnElement=skill&sortByElement=undefined&sortOrder=undefined',
    xt_06: '',
    xt_02:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=undefined&testId=undefined&sortOrder=asc',
    xt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
  },
  group: {
    r180_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_20: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180_13: '?sortOnElement=student&sortByElement=level&sortOrder=asc',
    r180_31tch: '',
    r180_31eng: '',
    r180_31hcr: '',
    r180_31hmo: '',
    r180_31spa: '',
    r180_31vie: '',
    r180_32tch: '',
    r180_32eng: '',
    r180_32hcr: '',
    r180_32hmo: '',
    r180_32spa: '',
    r180_32vie: '',
    r180_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_19: '',
    r180_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180_10: '',
    r180_28: '',
    r180_27: '',
    r180ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_11: '?sortOnElement=student&sortByElement=student&sortOrder=asc',
    r180ng_13: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_31tch: '',
    r180ng_31eng: '',
    r180ng_31hcr: '',
    r180ng_31hmo: '',
    r180ng_31spa: '',
    r180ng_31vie: '',
    r180ng_32tch: '',
    r180ng_32eng: '',
    r180ng_32hcr: '',
    r180ng_32hmo: '',
    r180ng_32spa: '',
    r180ng_32vie: '',
    r180ng_06: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_19: '',
    r180ng_07: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    r180ng_18: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    r180ng_10: '',
    r180ng_28: '',
    r180ng_27: '',
    rt_05: '',
    rt_04: '',
    rt_06: '',
    rt_02:
      '?sortOnElement=strand&sortByElement=desc&rstLevel=a&testBundleId=rSkills_Tests&stageLevel=A&sortOrder=asc',
    rt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    rtng_08: '',
    rtng_05: '',
    rtng_04: '',
    rtng_06: '',
    rtng_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
    s44_04:
      '?sortOnElement0=student&sortByElement0=name&sortOrder0=asc&sortOnElement1=nodata&sortByElement1=nodata&sortOrder1=nodata&sortOnElement2=nodata&sortByElement2=nodata&sortOrder2=nodata&sortOnElement3=nodata&sortByElement3=nodata&sortOrder3=nodata&sortOnElement4=nodata&sortByElement4=nodata&sortOrder4=nodata&sortOnElement5=nodata&sortByElement5=nodata&sortOrder5=nodata',
    s44_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_09: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    s44ng_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    phonics_inventory_01: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    phonics_inventory_03: '',
    phonics_inventory_02: '?sortOnElement=student&sortByElement=name&sortOrder=asc&testNumber=none',
    reading_counts_08:
      '?sortOnElement=student&sortByElement=name&awardLevel=Blue&awardType=Points&sortOrder=asc',
    reading_counts_10: '?sortOnElement=book&sortByElement=rank&sortOrder=asc',
    reading_counts_03: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_11:
      '?sortOnElement=student&sortByElement=undefined&quizName=undefined&sortOrder=undefined',
    reading_counts_17eng: '',
    reading_counts_17spa: '',
    reading_counts_18eng: '',
    reading_counts_18spa: '',
    reading_counts_19eng: '',
    reading_counts_19spa: '',
    reading_counts_20: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_14: '?sortOnElement=student&sortByElement=name&sortOrder=undefined',
    reading_counts_05: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_counts_16: '',
    reading_counts_04: '',
    reading_counts_06: '',
    reading_counts_15: '',
    reading_inventory_26: '',
    reading_inventory_27: '',
    reading_inventory_25: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_09: '?sortOnElement=student&sortByElement=growth&sortOrder=desc',
    reading_inventory_13: '?sortOnElement=student&sortByElement=performance_standard&sortOrder=asc',
    reading_inventory_19eng: '',
    reading_inventory_19spa: '',
    reading_inventory_20eng: '',
    reading_inventory_20spa: '',
    reading_inventory_10:
      '?sortOnElement=performance_standard&sortByElement=id&individualName=K&sortOrder=asc',
    reading_inventory_02: '',
    reading_inventory_23: '',
    reading_inventory_08: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_18: '',
    reading_inventory_14: '?sortOnElement=test&sortByElement=undefined&sortOrder=undefined',
    reading_inventory_15: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    reading_inventory_22: '',
    reading_inventory_12: '?sortOnElement=student&sortByElement=name&sortOrder=asc',
    xt_03: '',
    xt_05: '',
    xt_04: '?sortOnElement=skill&sortByElement=undefined&sortOrder=undefined',
    xt_06: '',
    xt_02:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=undefined&testId=undefined&sortOrder=asc',
    xt_01: '?sortOnElement=skill&sortByElement=desc&testId=undefined&sortOrder=undefined',
  },
  student: {
    dtm_01: '',
    dtm_03: '',
    fad_04: '',
    fad_12: '?sortOnElement=skill_category&sortByElement=id&sortOrder=asc',
    fad_07: '?sortOnElement=lesson&sortByElement=sequence_id&sortOrder=undefined',
    fm_01: '',
    fm_04: '?sortOnElement=daily_lessons&sortByElement=undefined&sortOrder=undefined',
    fm_03: '?sortOnElement=week_ending&sortByElement=undefined&sortOrder=undefined',
    fmng_01: '',
    fmng_04: '?sortOnElement=daily_lessons&sortByElement=undefined&sortOrder=undefined',
    fmng_03: '?sortOnElement=week_ending&sortByElement=undefined&sortOrder=undefined',
    math_inventory_08: '?sortOnElement=test&sortByElement=date&sortOrder=desc',
    math_inventory_09spa: '',
    math_inventory_09eng: '',
    math_inventory_07: '',
    r180ng_31tch: '',
    r180ng_31eng: '',
    r180ng_31hcr: '',
    r180ng_31hmo: '',
    r180ng_31spa: '',
    r180ng_31vie: '',
    r180ng_32tch: '',
    r180ng_32eng: '',
    r180ng_32hcr: '',
    r180ng_32spa: '',
    r180ng_32vie: '',
    r180ng_23: '?sortOnElement=skill&sortByElement=percentage&sortOrder=undefined',
    r180ng_10: '?sortOnElement=result&sortByElement=percentage&sortOrder=desc',
    r180ng_09: '',
    r180ng_28: '',
    r180ng_34: '',
    r180ng_27: '',
    rtng_05:
      '?sortOnElement=NA&sortByElement=test_id&sortOrder=asc&rubricSortByElement=test_id&rubricSortOrder=asc',
    rtng_04: '?sortOnElement=skill&sortByElement=desc&sortOrder=undefined',
    rtng_06: '',
    s44ng_01eng: '',
    s44ng_01spa: '',
    s44ng_ilp: '',
    s44ng_03: '',
    s44ng_07: '?sortOnElement0=topic&sortByElement0=topic_number&sortOrder0=undefined',
    phonics_inventory_03: '?sortOnElement=student&sortByElement=undefined&sortOrder=undefined',
    reading_counts_17eng: '',
    reading_counts_17spa: '',
    reading_counts_18eng: '',
    reading_counts_18spa: '',
    reading_counts_19eng: '',
    reading_counts_19spa: '',
    reading_counts_16: '?sortOnElement=genre&sortByElement=name&sortOrder=asc',
    reading_counts_04: '',
    reading_counts_06: '?sortOnElement=book&sortByElement=date&sortOrder=desc',
    reading_counts_15: '?sortOnElement=book&sortByElement=date&sortOrder=undefined',
    reading_inventory_27: '',
    reading_inventory_19eng: '',
    reading_inventory_19spa: '',
    reading_inventory_20eng: '',
    reading_inventory_20spa: '',
    reading_inventory_23: '',
    reading_inventory_18: '?sortOnElement=genre&sortByElement=name&sortOrder=asc',
    reading_inventory_14: '?sortOnElement=test&sortByElement=date&sortOrder=asc',
    reading_inventory_22: '',
    xt_05:
      '?sortOnElement=strand&sortByElement=sortID&courseLevel=undefined&testId=undefined&sortOrder=asc',
    xt_04: '?sortOnElement=skill&sortByElement=desc&sortOrder=asc',
    xt_06: '',
    r180_31tch: '',
    r180_31eng: '',
    r180_31hcr: '',
    r180_31hmo: '',
    r180_31spa: '',
    r180_31vie: '',
    r180_32tch: '',
    r180_32eng: '',
    r180_32hcr: '',
    r180_32hmo: '',
    r180_32spa: '',
    r180_32vie: '',
    r180_23: '?sortOnElement=skill&sortByElement=percentage&sortOrder=undefined',
    r180_10: '?sortOnElement=result&sortByElement=title&sortOrder=asc',
    r180_09: '',
    r180_28: '',
    r180_27: '',
    rt_05: '?noData=true',
    rt_04: '?sortOnElement=skill&sortByElement=desc&sortOrder=undefined',
    rt_06: '',
    s44_01eng: '',
    s44_01spa: '',
    s44_03: '',
    s44_07: '?sortOnElement0=topic&sortByElement0=topic_number&sortOrder0=undefined',
  },
};

export default PDFSort;
